name: ume_talk
description: Chat App.

version: 2.2.1+31

environment:
  sdk: ">=2.15.0-233.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core_platform_interface: ^4.5.1
  firebase_auth: ^4.2.2
  google_sign_in: ^6.0.2
  sign_in_with_apple: ^4.3.0
  cloud_firestore: ^4.5.0
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+4
  image_cropper: ^3.0.0
  shared_preferences: ^2.0.9
  firebase_storage: ^11.1.0
  cached_network_image: ^3.1.0+1
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^9.1.4
  photo_view: ^0.14.0
  cupertino_icons: ^1.0.4
  auto_size_text: ^3.0.0
  new_version: ^0.3.1
  rxdart: ^0.27.3
  image_gallery_saver: ^1.7.1
  dio: ^5.1.1
  flutter_app_badger: ^1.3.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  animated_splash_screen: ^1.2.0
  lottie: ^2.3.1
  provider: ^6.0.5
  url_launcher: ^6.1.10
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  package_info_plus: ^3.0.0
  win32: ^5.5.4

flutter:
  uses-material-design: true
  assets:
    - images/